
sudo: required
services:
- docker
language: bash
script:
# build image
- make docker
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    make
  else
    make docker
  fi
